# Generated by Django 2.0.6 on 2019-04-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_name', models.CharField(default='', max_length=225)),
                ('user_email', models.EmailField(default='', max_length=225, primary_key=True, serialize=False)),
                ('user_password', models.CharField(default='', max_length=20)),
                ('user_mobile', models.CharField(default='', max_length=255)),
                ('user_gender', models.CharField(default='', max_length=10)),
                ('user_isactive', models.BooleanField(default=True)),
                ('user_dob', models.CharField(default='', max_length=255)),
                ('user_image', models.CharField(default='', max_length=255, null=True)),
                ('user_isavailable', models.BooleanField(default=True)),
                ('user_isqueue', models.BooleanField(default=False)),
                ('role_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.Role')),
            ],
        ),
    ]
