# Generated by Django 2.0.6 on 2019-04-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdCategories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(default='', max_length=225, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(default='', max_length=255)),
                ('prod_price', models.CharField(default='', max_length=255)),
                ('prod_qty', models.CharField(default='', max_length=55)),
                ('prod_image', models.CharField(default='', max_length=220, null=True)),
                ('prod_creationdate', models.DateField()),
                ('cat_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ProdCategories')),
                ('type_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ProdType')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.UserDetail')),
            ],
        ),
    ]
