# Generated by Django 2.0.6 on 2019-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_prodcategories_prodtype_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_creationdate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
