# Generated by Django 2.0.6 on 2019-04-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190410_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdBrand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default='', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdSize',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(default='', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ProdType')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_name',
            new_name='user_email',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img2',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img3',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img4',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ProdBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ProdSize'),
        ),
    ]
