# Generated by Django 2.0.6 on 2019-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190410_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_description',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
