# Generated by Django 2.0.6 on 2019-04-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_product_prod_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='date_reg',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='otp',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
