# Generated by Django 2.0.6 on 2019-04-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190412_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_name',
            new_name='user_fname',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='otp_time_gen',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_isverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_lname',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_token',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
