# Generated by Django 2.0.6 on 2019-05-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190501_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_image',
        ),
    ]
