# Generated by Django 2.0.6 on 2019-05-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_product_prod_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProduct',
            fields=[
                ('tempproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(default='', max_length=255)),
                ('prod_qty', models.IntegerField()),
                ('prod_price', models.IntegerField()),
                ('user_email', models.CharField(default='', max_length=255, null=True)),
                ('prod_size', models.CharField(max_length=25)),
                ('prod_type', models.CharField(max_length=25)),
                ('prod_cat', models.CharField(max_length=25)),
                ('add_date', models.CharField(max_length=255, null=True)),
                ('prod_image', models.CharField(max_length=255, null=True)),
                ('subtotal', models.IntegerField()),
            ],
        ),
    ]
