# Generated by Django 2.0.6 on 2019-05-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_tempproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTable',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.CharField(max_length=35)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(default='', max_length=255)),
                ('prod_qty', models.IntegerField()),
                ('prod_price', models.IntegerField()),
                ('user_email', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=55)),
                ('prod_size', models.CharField(max_length=255, null=True)),
                ('prod_type', models.CharField(max_length=25)),
                ('prod_cat', models.CharField(max_length=25)),
                ('total', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=35)),
                ('sale_date', models.CharField(max_length=35)),
                ('user_address', models.CharField(max_length=255)),
                ('user_landmark', models.CharField(max_length=30)),
                ('user_mobile', models.CharField(max_length=55)),
                ('user_pincode', models.CharField(max_length=25)),
            ],
        ),
    ]
