# Generated by Django 2.0.6 on 2019-05-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_saletable'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletable',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saletable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
