# Generated by Django 2.0.6 on 2019-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20190514_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(default='', max_length=255)),
                ('token', models.CharField(default='', max_length=255)),
                ('invoice', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
    ]
